# -*- coding: utf-8 -*-
"""rotten.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6g5POVy0SDhb66fhBqwWXf7uIYpDAHm
"""

import requests
from bs4 import BeautifulSoup
basesite="https://editorial.rottentomatoes.com/guide/140-essential-action-movies-to-watch-now/"
response=requests.get(basesite)
response

html=response.content
soup=BeautifulSoup(html,'lxml')
print(soup.prettify()[:1000])
soup

divs=soup.find_all('div',{'class':"col-sm-18 col-full-xs countdown-item-content"})
divs

headings=[div.find("h2") for div in divs]
headings

headings[0]

movienames=[heading.find('a').string for heading in headings]
movienames

scores=[heading.find('span',class_='tMeterScore').string for heading in headings]
scores

consensus=[div.find("div",{"class":"info critics-consensus"}) for div in divs]
consensus

[con.text for con in consensus]

commonphrase='Critics Consensus: '
len(commonphrase)

consensus[0].text[19:]

commonlen=len(commonphrase)
consensustext=[con.text[commonlen:] for con in consensus]
consensustext



years=[heading.find('span',class_='start-year').string for heading in headings]
years

years[0].strip('(')

years[0].strip(')')

years[0].strip('()')

years=[year.strip('()') for year in years]
years

years=[int(year) for year in years]
years

consensus[0]

consensus[0].contents[3].strip()

castinfo=[div.find("div",class_='cast') for div in divs]

castinfo

castinfo[0]

castlinks=castinfo[0].find_all('a')
castlinks

cast_names=[link.string for link in castlinks]
cast_names

cast=", ".join(cast_names)
cast

cast=[]


for c in castinfo:
  castlinks=c.find_all('a')
  cast_names=[link.string for link in castlinks]
  result=", ".join(cast_names)
  cast.append(result)
  
cast

cast=[", ".join(link.string for link in c.find_all('a')) for c in castinfo]
cast

import pandas as pd

moviesinfo=pd.DataFrame()
moviesinfo["movie title"]=movienames
moviesinfo["year"]=years
moviesinfo["score"]=scores
moviesinfo["cast"]=cast
moviesinfo["consensus"]=consensustext


moviesinfo

pd.set_option('display.max_colwidth',-1)
moviesinfo

moviesinfo.to_csv("moviesinfo.csv",index=False,header=True)
moviesinfo.to_excel("movieinfo.xlsx",index=False,header=True)
from google.colab import files
files.download("movieinfo.xlsx")